<a href="https://colab.research.google.com/github/SRET-College/Sem-6-NN-and-DL/blob/main/NN_and_DL_Expt_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Step 2: Define input data (AND logic)
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

# Step 3: Define expected output
y = np.array([[0],
              [0],
              [0],
              [1]])

# Step 4: Initialize weights and bias randomly
weights = np.random.rand(2, 1)
bias = np.random.rand(1)

# Step 5: Define activation function (Sigmoid)
def sigmoid(x):
    return 1/(1 + np.exp(-x))

# Step 6: Define derivative of sigmoid
def sigmoid_derivative(x):
    return x * (1 - x)

# Step 7: Training parameters
learning_rate = 0.1
epochs = 10000

# Step 8: Training the neural network
for epoch in range(epochs):
    # Forward propagation
    z = np.dot(X, weights) + bias
    output = sigmoid(z)

    # Calculate error
    error = y - output

    # Backpropagation
    d_output = error * sigmoid_derivative(output)

    # Update weights and bias
    weights += learning_rate * np.dot(X.T, d_output)
    bias += learning_rate * np.sum(d_output)

print("Final Weights:\n", weights)
print("Final Bias:\n", bias)

binary_output = (output >= 0.5).astype(int)
print("\nPredicted Output after Training:\n", binary_output)

Final Weights:
 [[5.47785198]
 [5.47785197]]
Final Bias:
 [-8.30947707]

Predicted Output after Training:
 [[0]
 [0]
 [0]
 [1]]


In [3]:
from sklearn.linear_model import Perceptron
import numpy as np

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 0, 0, 1])

model = Perceptron(max_iter=1000, eta0=0.01, random_state=1)
model.fit(X, y)

print("Predicted Output:", model.predict(X))

Predicted Output: [0 0 0 1]


In [4]:
# Expected output for OR logic
y = np.array([[0], [1], [1], [1]])

# ... (Steps 4-8 remain same as AND gate implementation) ...

binary_output = (output >= 0.5).astype(int)
print("Predicted Output after Training:\n", binary_output)

Predicted Output after Training:
 [[0]
 [0]
 [0]
 [1]]


In [5]:
y = np.array([0, 1, 1, 1])
model = Perceptron(max_iter=1000, eta0=0.01, random_state=1)
model.fit(X, y)
print("Predicted Output:", model.predict(X))

Predicted Output: [0 1 1 1]


In [6]:
X = np.array([[0], [1]])
y = np.array([[1], [0]])

weights = np.random.rand(1, 1)
bias = np.random.rand(1)


In [7]:
import numpy as np

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

np.random.seed(1)
W1 = np.random.rand(2, 2) # Input to Hidden
b1 = np.random.rand(1, 2)
W2 = np.random.rand(2, 1) # Hidden to Output
b2 = np.random.rand(1)

learning_rate = 0.1
epochs = 10000

for epoch in range(epochs):
    # Forward Propagation
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    output = sigmoid(z2)

    # Backpropagation
    error = y - output
    d_output = error * sigmoid_derivative(output)
    d_hidden = np.dot(d_output, W2.T) * sigmoid_derivative(a1)

    # Updates
    W2 += learning_rate * np.dot(a1.T, d_output)
    b2 += learning_rate * np.sum(d_output)
    W1 += learning_rate * np.dot(X.T, d_hidden)
    b1 += learning_rate * np.sum(d_hidden, axis=0, keepdims=True)

print("Predicted Output after Training:\n", output.round())

Predicted Output after Training:
 [[0.]
 [1.]
 [1.]
 [0.]]


In [8]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(4,), activation='logistic', solver='lbfgs', max_iter=10000, random_state=1)
mlp.fit(X, y.ravel())
print("Predicted Output after Training:", mlp.predict(X))

Predicted Output after Training: [0 1 1 0]
